###服务启动端口号
server:
  port: 9999

###服务名称
spring:

  application:
    name: app-lesson3
  datasource:
    username: mdmuser
    password: Mdm1219
    url: jdbc:mysql://10.253.7.54:3306/mdm90?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database:0
    host:127.0.0.1
    port:6379
    timeout:2000
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  enable-method-annotation: true #是否可以用
  identity: MYSQL  # 生成id的方法
  platform: mysql
  type: com.alibaba.druid.pool.DruidDataSource
  #下面为连接池的补充设置，应用到上面所有数据源中
  # 初始化大小，最小，最大
  initialSize: 1
  minIdle: 3
  maxActive: 20
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 30000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20

#pagehelper分页配置 第二种和第三种不需要 重点讲的第一种需要
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#日志级别
logging:
  level:
    cn:
      dazd:debug



